# Generated by Django 3.0.6 on 2020-05-31 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityPeriods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.CharField(editable=False, max_length=9, primary_key=True, serialize=True)),
                ('real_name', models.CharField(max_length=50)),
                ('tz', models.CharField(max_length=35)),
                ('activity_periods', models.ManyToManyField(to='api.ActivityPeriods')),
            ],
        ),
    ]
